sessionId: crawl-1760944806706-fbnjpo0mvxt
host: https://gitlab.com
accountId: config
startedAt: '2025-10-20T07:20:06.706Z'
lastUpdate: '2025-10-20T07:21:59.536Z'
currentStep: areas
completedSteps: []
steps:
  areas:
    groups:
      step: areas
      subStep: groups
      completed: false
      cursor: eyJuYW1lIjoiMDAxZDc4Y2E1NWI2ZmZmNjU3YTgwOTFlIiwiaWQiOiIxMTI2MDkwMzYifQ
      itemsProcessed: 560
      totalItems: 560
      lastUpdate: '2025-10-20T07:21:59.536Z'
