query FetchProject($fullPath: ID!) {
  project(fullPath: $fullPath) {
    id
    name
    path
    fullPath
    description
    visibility
    createdAt
    updatedAt
    lastActivityAt
    webUrl
    avatarUrl
    archived
    forksCount
    starCount
    issuesEnabled
    mergeRequestsEnabled
    wikiEnabled
    snippetsEnabled
    containerRegistryEnabled
    lfsEnabled
    requestAccessEnabled
    nameWithNamespace
    topics
    repository {
      exists
      empty
      rootRef
    }
    statistics {
      commitCount
      storageSize
      repositorySize
      lfsObjectsSize
      buildArtifactsSize
      packagesSize
      snippetsSize
      uploadsSize
    }
  }
}
