query FetchGroupProjects($fullPath: ID!, $first: Int, $after: String) {
  group(fullPath: $fullPath) {
    projects(first: $first, after: $after) {
      pageInfo {
        hasNextPage
        endCursor
      }
      nodes {
        id
        name
        path
        fullPath
        description
        visibility
        createdAt
        updatedAt
        lastActivityAt
        webUrl
        avatarUrl
        archived
        forksCount
        starCount
        issuesEnabled
        mergeRequestsEnabled
        wikiEnabled
        snippetsEnabled
        containerRegistryEnabled
        lfsEnabled
        requestAccessEnabled
        nameWithNamespace
        topics
      }
    }
  }
}
