query FetchGroups($first: Int, $after: String) {
  groups(first: $first, after: $after) {
    pageInfo {
      hasNextPage
      endCursor
    }
    nodes {
      id
      name
      path
      fullName
      fullPath
      description
      visibility
      createdAt
      updatedAt
      webUrl
      avatarUrl
      parent {
        id
        fullPath
      }
      subgroupCreationLevel
      projectCreationLevel
    }
  }
}
