query FetchSubgroups($fullPath: ID!, $first: Int, $after: String) {
  group(fullPath: $fullPath) {
    descendantGroups(first: $first, after: $after) {
      pageInfo {
        hasNextPage
        endCursor
      }
      nodes {
        id
        name
        path
        fullName
        fullPath
        description
        visibility
        createdAt
        updatedAt
        webUrl
        avatarUrl
        parent {
          id
          fullPath
        }
        subgroupCreationLevel
        projectCreationLevel
      }
    }
  }
}
