query FetchGroup($id: ID!) {
  group(id: $id) {
    id
    name
    path
    fullName
    fullPath
    description
    visibility
    createdAt
    updatedAt
    webUrl
    avatarUrl
    parentId
    subgroupCreationLevel
    projectCreationLevel
    repositorySizeLimit
    lfsEnabled
    requestAccessEnabled
    fullName
    fullPath
    rootStorageStatistics {
      storageSize
      repositorySize
      lfsObjectsSize
      buildArtifactsSize
      packagesSize
      snippetsSize
      uploadsSize
    }
  }
}
