query FetchGroup($fullPath: ID!) {
  group(fullPath: $fullPath) {
    id
    name
    path
    fullName
    fullPath
    description
    visibility
    createdAt
    updatedAt
    webUrl
    avatarUrl
    parent {
      id
      fullPath
    }
    subgroupCreationLevel
    projectCreationLevel
    actualRepositorySizeLimit
    lfsEnabled
    requestAccessEnabled
    rootStorageStatistics {
      storageSize
      repositorySize
      lfsObjectsSize
      buildArtifactsSize
      packagesSize
      snippetsSize
      uploadsSize
    }
  }
}
